### ISSUE TITLE
Request for Twitter Handle

### ISSUE THREAD

**Issue by 2manslkh** [ysjprojects/eth-singapore#1]
Hi @francisco-leal @ysjprojects,

Congratulations for winning a Taiko Bounty at ETH Singapore! We would like to showcase your project on twitter. Would you please provide your twitter handle for us?

**Comment by 0xleal** [comment]
Sure! This is my twitter: https://twitter.com/Francisco__Leal

**Comment by ysjprojects** [comment]
here is mine!
https://twitter.com/web3dotsj
